# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'KD Tiktok-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for KD Tiktok-Clone
  pod 'SnapKit'
  pod 'RxSwift', '~> 5'
  pod 'lottie-ios'

  target 'KD Tiktok-CloneTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
